// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI-Uk6IW54nMvBgxX7CPsgx0lMo58otfQ',
    appId: '1:163954857780:web:60fbaf5d9cb54115ae3761',
    messagingSenderId: '163954857780',
    projectId: 'devfestlagos-2022',
    authDomain: 'devfestlagos-2022.firebaseapp.com',
    storageBucket: 'devfestlagos-2022.appspot.com',
    measurementId: 'G-CR8TKECQD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyucrDWB2TK6bLcne65YcihOBVBHLjMtI',
    appId: '1:163954857780:android:514c9330015df742ae3761',
    messagingSenderId: '163954857780',
    projectId: 'devfestlagos-2022',
    storageBucket: 'devfestlagos-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjQGvrhDQTdVk5-DInHkDLMiOgvzHoxI',
    appId: '1:163954857780:ios:82a351792fa59e26ae3761',
    messagingSenderId: '163954857780',
    projectId: 'devfestlagos-2022',
    storageBucket: 'devfestlagos-2022.appspot.com',
    iosClientId: '163954857780-vo9kvg7ntmka55454t4s8549ricv3cq5.apps.googleusercontent.com',
    iosBundleId: 'google.devfest2022.devfest',
  );
}
