// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoK1FPg7hjP7xvQVnDutrXYOfpQ20ThbM',
    appId: '1:139760166020:web:4748970e6c63c349bb8ed1',
    messagingSenderId: '139760166020',
    projectId: 'devfest-lagos-2022',
    authDomain: 'devfest-lagos-2022.firebaseapp.com',
    storageBucket: 'devfest-lagos-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1O0HLhFPHnLj-12S8sDU9jMg3W_ulZY',
    appId: '1:139760166020:android:62830c772acbbdf2bb8ed1',
    messagingSenderId: '139760166020',
    projectId: 'devfest-lagos-2022',
    storageBucket: 'devfest-lagos-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5HL5qOmBduWu_BjDeTSNcC-TYk9Qx2Y',
    appId: '1:139760166020:ios:1907c9e9c82245ddbb8ed1',
    messagingSenderId: '139760166020',
    projectId: 'devfest-lagos-2022',
    storageBucket: 'devfest-lagos-2022.appspot.com',
    iosClientId:
        '139760166020-7de8n1epkf7tmsopp9u63icm5r84f3vs.apps.googleusercontent.com',
    iosBundleId: 'google.devfest2022.devfest',
  );
}
